blank_issues_enabled: false
contact_links:
  - name: 💬 General Discussion
    url: https://github.com/paulinmemphis/fathom/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Issues
    url: https://github.com/paulinmemphis/fathom/security/advisories/new
    about: Report security vulnerabilities privately