name: iOS CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer
      
    - name: Build
      run: |
        xcodebuild -project Fathom.xcodeproj \
                   -scheme Fathom \
                   -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' \
                   clean build
                   
    - name: Test
      run: |
        xcodebuild -project Fathom.xcodeproj \
                   -scheme Fathom \
                   -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' \
                   test
                   
    - name: Archive build logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          ~/Library/Logs/DiagnosticReports/
          *.log